//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\Response\VSAR\NXProject\AppRoot\application\Solve.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: wujif
//              Version: NX 7.5
//              Date: 05-23-2011  (Format: mm-dd-yyyy)
//              Time: 20:48
//
//==============================================================================

#ifndef VSARUI_SOLVE_H_INCLUDED
#define VSARUI_SOLVE_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <VsarUI_BaseDialog.hxx>

//------------------------------------------------------------------------------
// Forward declaration for Class
//------------------------------------------------------------------------------
namespace VsarUI
{
    class Solve : public BaseDialog
    {
        // class members
    public:
        Solve();
        ~Solve();

        static void ShowDialog();

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the Solve.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb();
        virtual void DialogShownCb();
        virtual int ApplyCb();
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* block);

    private:
        //NXOpen::BlockStyler::UIBlock* trainSettingsGrp;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_trainSpeed;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_timeStep;// Block type: Expression

        //NXOpen::BlockStyler::UIBlock* outputGrp;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_hasTimeOutput;// Block type: Toggle
        NXOpen::BlockStyler::UIBlock* m_outputTime;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_hasNodesOutput;// Block type: Toggle
        NXOpen::BlockStyler::UIBlock* m_outputNode;// Block type: Select Nodes

    };
}
#endif //VSARUI_SOLVE_H_INCLUDED
