//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\Response\VSAR\NXProject\AppRoot\application\TrainSettings.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: wujif
//              Version: NX 7.5
//              Date: 04-08-2011  (Format: mm-dd-yyyy)
//              Time: 21:59
//
//==============================================================================

#ifndef VSARUI_TRAINSETTINGS_H_INCLUDED
#define VSARUI_TRAINSETTINGS_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <VsarUI_BaseCompDialog.hxx>

namespace VsarUI
{
    class TrainSettings : public BaseCompDialog
    {
        // class members
    public:

        TrainSettings();
        ~TrainSettings();

        static void ShowDialog();

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the TrainSettings.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb();
        virtual void DialogShownCb();
        //virtual int ApplyCb();
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* block);

    private:

        //  Carriage group
        //NXOpen::BlockStyler::UIBlock* m_grpCarriage;// Block type: Group

        NXOpen::BlockStyler::UIBlock* m_carriageCount;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_carriageLength;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_carriageDistance;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_carriageWeight;// Block type: Expression

        // bogie group
        //NXOpen::BlockStyler::UIBlock* m_grpBogie;// Block type: Group

        NXOpen::BlockStyler::UIBlock* m_bogieLength;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_halfBogieDistance;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_bogieWeight;// Block type: Expression

        // wheel set group
        //NXOpen::BlockStyler::UIBlock* m_grpWheelSet;// Block type: Group

        NXOpen::BlockStyler::UIBlock* m_wheelSetInterval;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetWeight;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetSglStgSusp;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetSglStgSuspDamp;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetTwoStgSuspStiff;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetTwoStgSuspDamp;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_wheelSetContactCoefElast;// Block type: Expression
    };
}
#endif //VSARUI_TRAINSETTINGS_H_INCLUDED
