//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\Response\VSAR\NXProject\AppRoot\application\Vsar_BaseDialog.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: wujif
//              Version: NX 7.5
//              Date: 02-19-2011  (Format: mm-dd-yyyy)
//              Time: 17:32
//
//==============================================================================

#ifndef VSARUI_BASEDIALOG_H_INCLUDED
#define VSARUI_BASEDIALOG_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <string>

#include <boost/scoped_ptr.hpp>

#include <NXOpen/BlockStyler_BlockDialog.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
// Forward declaration for Class
//------------------------------------------------------------------------------
namespace NXOpen
{
    class Session;
    class UI;
    class TaggedObject;

    namespace BlockStyler
    {
        class UIBlock;
        class BlockDialog;
    }
}

namespace VsarUI
{
    class BaseDialog
    {
        // class members
    public:
        static NXOpen::Session *theSession;
        static NXOpen::UI      *theUI;

        int Show(NXOpen::BlockStyler::BlockDialog::DialogMode dialogMode = NXOpen::BlockStyler::BlockDialog::DialogModeCreate);

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the Vsar_BaseDialog.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb() = 0;
        virtual void DialogShownCb();
        virtual int ApplyCb();
        virtual int OkCb();
        virtual int CancelCb();
        virtual int FilterCb(NXOpen::BlockStyler::UIBlock *pBlock, NXOpen::TaggedObject *pSel);
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* pBlock);
        virtual void FocusNotifyCb(NXOpen::BlockStyler::UIBlock* pBlock, bool focus);
        virtual void KeyboardFocusNotifyCb(NXOpen::BlockStyler::UIBlock* pBlock, bool focus);

    protected:
        BaseDialog(const std::string &dialogName);
        virtual ~BaseDialog();

    protected:

        boost::scoped_ptr<NXOpen::BlockStyler::BlockDialog> m_theDialog;
    };
}

//#if defined(__MSVC_RUNTIME_CHECKS)
//#undef __MSVC_RUNTIME_CHECKS
//#endif

//#if !defined(_DEBUG)
//#define _DEBUG
//#endif

#endif //VSARUI_BASEDIALOG_H_INCLUDED
