//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\CAE\Response\VSAR-DEV\NXProject\AppRoot\application\SlabSettings.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Joseph
//              Version: NX 7.5
//              Date: 05-08-2011  (Format: mm-dd-yyyy)
//              Time: 14:00
//
//==============================================================================

#ifndef VSARUI_SLABSETTINGS_H_INCLUDED
#define VSARUI_SLABSETTINGS_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <VsarUI_BaseCompDialog.hxx>

//------------------------------------------------------------------------------
// Forward declaration for Class
//------------------------------------------------------------------------------

namespace VsarUI
{
    class SlabSettings : public BaseCompDialog
    {
        // class members
    public:
        SlabSettings();
        ~SlabSettings();

        static void ShowDialog();

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the SlabSettings.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb();
        virtual void DialogShownCb();
        //int ApplyCb();
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* block);

    private:

        //NXOpen::BlockStyler::UIBlock* grpGeometry;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_length;// Block type: Expression
        //NXOpen::BlockStyler::UIBlock* m_eleSize;// Block type: Expression
        //NXOpen::BlockStyler::UIBlock* counts;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_supportCnt;// Block type: Enumeration

        //NXOpen::BlockStyler::UIBlock* grpMaterial;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_fastenerStiffness;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_fastenerDamping;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_massRatio;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_stiffnessRatio;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_dampingRatio;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_elasticModulus;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_crossSectMomentInertia;// Block type: Expression
    };
}

#endif //VSARUI_SLABSETTINGS_H_INCLUDED
