//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\Response\VSAR\NXProject\AppRoot\application\RailSettings.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: wujif
//              Version: NX 7.5
//              Date: 05-07-2011  (Format: mm-dd-yyyy)
//              Time: 22:11 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <VsarUI_RailSettings.hxx>

#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>

#include <Vsar_Component.hxx>
#include <Vsar_Init_Utils.hxx>


using namespace NXOpen;
using namespace NXOpen::BlockStyler;
using namespace Vsar;

namespace VsarUI
{
    static CompAttrInfo attrExpInfo[] =
    {
        {"density",                     "RailSlab_f", "Rail_Density"},
        {"elasticModulus",              "RailSlab_f", "Rail_Elastic_Modulus"},
        {"crossSectMomentInertia",      "RailSlab_f", "Rail_CrossSect_MomentInertia"}
    };

    //------------------------------------------------------------------------------
    // Constructor for NX Styler class
    //------------------------------------------------------------------------------
    RailSettings::RailSettings() : BaseCompDialog("RailSettings.dlx",
                                                  new BaseComponent(attrExpInfo, N_ELEMENTS(attrExpInfo)))
    {
    }

    //------------------------------------------------------------------------------
    // Destructor for NX Styler class
    //------------------------------------------------------------------------------
    RailSettings::~RailSettings()
    {
    }

    void RailSettings::ShowDialog()
    {
        boost::scoped_ptr<RailSettings> pRailSettingDlg(new RailSettings());

        try
        {
            // The following method shows the dialog immediately
            pRailSettingDlg->Show(BlockDialog::DialogModeEdit);
        }
        catch(std::exception& ex)
        {
            //---- Enter your exception handling code here -----
            theUI->NXMessageBox()->Show("Block Styler", NXMessageBox::DialogTypeError, ex.what());
        }
    }

    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------

    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    void RailSettings::InitializeCb()
    {
        BaseCompDialog::InitializeCb();

        try
        {
            CompositeBlock *pTopBlock = m_theDialog->TopBlock();

            //grpGeometry = pTopBlock->FindBlock("grpGeometry");
            m_length = pTopBlock->FindBlock("length");
            m_width = pTopBlock->FindBlock("width");
            m_eleSize = pTopBlock->FindBlock("eleSize");

            //grpMaterial = pTopBlock->FindBlock("grpMaterial");
            m_density = pTopBlock->FindBlock("density");
            m_elasticModulus = pTopBlock->FindBlock("elasticModulus");
            m_crossSectMomentInertia = pTopBlock->FindBlock("crossSectMomentInertia");
        }
        catch(std::exception& ex)
        {
            //---- Enter your exception handling code here -----
            theUI->NXMessageBox()->Show("Block Styler", NXMessageBox::DialogTypeError, ex.what());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    void RailSettings::DialogShownCb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch(std::exception& ex)
        {
            //---- Enter your exception handling code here -----
            theUI->NXMessageBox()->Show("Block Styler", NXMessageBox::DialogTypeError, ex.what());
        }
    }

    //------------------------------------------------------------------------------
    //Callback Name: apply_cb
    //------------------------------------------------------------------------------
    //int RailSettings::ApplyCb()
    //{
    //    int errorCode = 0;
    //    try
    //    {
    //        BaseCompDialog::ApplyCb();
    //    }
    //    catch(std::exception& ex)
    //    {
    //        //---- Enter your exception handling code here -----
    //        errorCode = 1;
    //        theUI->NXMessageBox()->Show("Block Styler", NXMessageBox::DialogTypeError, ex.what());
    //    }
    //    return errorCode;
    //}

    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    int RailSettings::UpdateCb(UIBlock* block)
    {
        try
        {
            if(block == m_length)
            {
                //---------Enter your code here-----------
            }
            else if(block == m_width)
            {
                //---------Enter your code here-----------
            }
            else if(block == m_eleSize)
            {
                //---------Enter your code here-----------
            }
            else if(block == m_density)
            {
                //---------Enter your code here-----------
            }
            else if(block == m_elasticModulus)
            {
                //---------Enter your code here-----------
            }
            else if(block == m_crossSectMomentInertia)
            {
                //---------Enter your code here-----------
            }
        }
        catch(std::exception& ex)
        {
            //---- Enter your exception handling code here -----
            theUI->NXMessageBox()->Show("Block Styler", NXMessageBox::DialogTypeError, ex.what());
        }
        return 0;
    }
}
