/*HEAD LIBVSARINIT_EXPORTS HHH VSARINIT */
/*=============================================================================
File description:

    This contains the export symbols for the LIBVSARINIT library.

    Documentation at http://cipgweb/do/devops_nx:relnotes:autogenerated_export_headers

    Autogenerated by //nx/nx8/build/tools/be/GenerateExportsHeaders.pm#3

==============================================================================*/
#ifndef LIBVSARINIT_EXPORTS_H_INCLUDED
#define LIBVSARINIT_EXPORTS_H_INCLUDED

#ifdef USE_PRAGMA_ONCE
#pragma once
#endif

//#if IPLIB==10
#if defined (LIBVSARINIT)
#   if defined(_WIN32)
#       define VSARINITEXPORT       __declspec(dllexport)
#       define VSARINITGLOBAL       extern __declspec(dllexport)
#   elif __GNUC__ >= 4
#       define VSARINITEXPORT       __attribute__ ((visibility("default")))
#       define VSARINITGLOBAL       extern __attribute__ ((visibility("default")))
#   else
#       define VSARINITEXPORT
#       define VSARINITGLOBAL       extern
#   endif
#else
#   if defined(_WIN32) && !defined(WNT_STATIC_LINK)
#       define VSARINITEXPORT       __declspec(dllimport)
#       define VSARINITGLOBAL       extern __declspec(dllimport)
#   else
#       define VSARINITEXPORT
#       define VSARINITGLOBAL       extern
#   endif
#endif

#endif  /* LIBVSARINIT_EXPORTS_H_INCLUDED */
