//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\Response\VSAR\NXProject\AppRoot\application\Vsar_NewProject.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: wujif
//              Version: NX 7.5
//              Date: 02-19-2011  (Format: mm-dd-yyyy)
//              Time: 17:32
//
//==============================================================================

#ifndef VSARUI_NEWPROJECT_H_INCLUDED
#define VSARUI_NEWPROJECT_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <VsarUI_BaseDialog.hxx>

namespace VsarUI
{
    class NewProject : public BaseDialog
    {
        // class members
    public:

        NewProject();
        ~NewProject();

        static void ShowDialog();

        //void RegisterWithMenu();

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the Vsar_NewProject.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb();
        virtual void DialogShownCb();
        virtual int ApplyCb();
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* block);

    private:

        //NXOpen::BlockStyler::UIBlock* m_prjGroup;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_prjName;// Block type: String
        NXOpen::BlockStyler::UIBlock* m_prjPath;// Block type: NativeFolderBrowser
        //NXOpen::BlockStyler::UIBlock* m_group;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_prjType;// Block type: Enumeration
        NXOpen::BlockStyler::UIBlock* m_typeImg;// Block type: Label

    };
}

#endif //VSARUI_NEWPROJECT_H_INCLUDED
