//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  E:\Project\CAE\Response\VSAR-DEV\NXProject\AppRoot\application\BridgeSettings.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Joseph
//              Version: NX 7.5
//              Date: 05-08-2011  (Format: mm-dd-yyyy)
//              Time: 14:03
//
//==============================================================================

#ifndef VSARUI_BRIDGESETTINGS_H_INCLUDED
#define VSARUI_BRIDGESETTINGS_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <VsarUI_BaseCompDialog.hxx>

//------------------------------------------------------------------------------
// Forward declaration for Class
//------------------------------------------------------------------------------

namespace VsarUI
{
    class BridgeSettings : public BaseCompDialog
    {
        // class members
    public:
        BridgeSettings();
        ~BridgeSettings();

        static void ShowDialog();

        //----------------------- BlockStyler Callback Prototypes ---------------------
        // The following member function prototypes define the callbacks 
        // specified in your BlockStyler dialog.  The empty implementaiton
        // of these prototypes is provided in the BridgeSettings.cpp file. 
        // You are REQUIRED to write the implementation for these funtions.
        //------------------------------------------------------------------------------
        virtual void InitializeCb();
        virtual void DialogShownCb();
        //int ApplyCb();
        virtual int UpdateCb(NXOpen::BlockStyler::UIBlock* block);

    private:
        //NXOpen::BlockStyler::UIBlock* grpGeometric;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_width;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_height;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_spanCnt;// Block type: Enumeration

        //NXOpen::BlockStyler::UIBlock* grpMaterial;// Block type: Group
        NXOpen::BlockStyler::UIBlock* m_elasticModulus;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_massDensity;// Block type: Expression
        NXOpen::BlockStyler::UIBlock* m_poissonRatio;// Block type: Expression
    };
}
#endif //VSARUI_BRIDGESETTINGS_H_INCLUDED
